pipeline{
    agent any
    stages{
        stage('uptime'){
            steps{
                sh '''
                   uptime
                '''
            }
        }
         stage('Ram-Used'){
            steps{
                sh '''
                   free -h
                '''
            }
        }
         stage('disk-file'){
            steps{
                sh '''
                   df -kh
                '''
            }
        }
        stage('poll-scm-checkin'){
            steps{
                sh '''
                   echo "Checking wheather poll scm works or not"
                '''
            }
        }
    }
}