pipeline{
    agent any
    stages{
        stage('uptime'){
            steps{
                sh '''
                   uptime
                '''
            }
        }
         stage('Ram-Used'){
            steps{
                sh '''
                   free -h
                '''
            }
        }
         stage('disk-file'){
            steps{
                sh '''
                   df -kh
                '''
            }
        }
    }
}